version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
# in the VM it should be 443, but on the macs we cant use priveliged ports.
      # - 443:443
      - 9001:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

  wordpress:
    container_name: wordpress

    depends_on:
      # - mariadb
      - nginx
    build: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network



volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jboeve/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jboeve/data/wordpress
      o: bind

networks:
  network:
    driver: bridge
