
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ~/docker_volumes/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ~/docker_volumes/wordpress
      o: bind

networks:
  network:
    driver: bridge


services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - mariadb
    networks:
      - network
    env_file:
      - .env

  nginx:
    container_name: nginx
    env_file:
      - .env
    build: ./requirements/nginx
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network
    ports:
      # - 443:443
      - 9001:443

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env


