services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
# in the VM it should be 443, but on the macs we cant use priveliged ports.
      # - 443:443
      - 9001:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - wordpress
    networks:
      - network





volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ~/docker_volumes/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ~/docker_volumes/wordpress
      o: bind

networks:
  network:
    driver: bridge
