
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind

networks:
  network:
    driver: bridge


services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
        required: true 
    networks:
      - network
    env_file:
      - .env

  nginx:
    container_name: nginx
    env_file:
      - .env
    build: ./requirements/nginx
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - wordpress
    networks:
      - network
    ports:
      - 443:443

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "/etc/healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2s
      start_interval: 5s


