version: '3'

services:

  mariadb:
    container_name: mariadb
    # path to file that contains `Dockerfile`
    build: ./containers/mariadb
    #volumes allow to store in a persistent disk the content in a local disk
    #db_data is a volume created by docker directly
    volumes:
      - mariadb_data:/var/lib/mysql
    # in case of problem we restart automatically the container
    # networks:
    #   - network
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env




#
# networks:
#   network:
#     driver: bridge
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jboeve/data/mysql
      o: bind
